title: Chris Tulsi
logo: https://media.licdn.com/dms/image/C4E03AQE4IqFoUXTCnw/profile-displayphoto-shrink_800_800/0/1565896162743?e=1717027200&v=beta&t=6tZUil60MrMQVSastDSxAPeJw8ihhQg5S21yZeFVqfc
description: Software Engineer
show_downlads: true
google_analytics: G-FTYWQEZ9SL
theme: jekyll-theme-minimal
